services:
  backend:
    build: ./backend
    image: skills-app
    container_name: backend
    volumes:
      - ./backend:/app
      - models:/models


    depends_on:
      - qdrant
    ports:
      - "8000:80"
    restart: unless-stopped
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API: /api
    environment:
      VITE_API: /api
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
  models:
