services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    depends_on:
      - qdrant
    restart: unless-stopped
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data: