services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: skills-app
    container_name: backend
    volumes:
      - models:/models

    depends_on:
      - qdrant
    restart: unless-stopped
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      WEB_URL: ${WEB_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API: /api
    environment:
      VITE_API: /api
      WEB_URL: ${WEB_URL}
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
  models:
  postgres:
