services:
  backend:
    image: registry.skillsnavigator.ru/skills-app-backend:${TAG}
    container_name: backend
    build:
      context: ./backend
    volumes:
      - models:/models
    depends_on:
      - qdrant
    restart: always
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      WEB_URL: ${WEB_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SECRET_KEY: ${SECRET_KEY}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}

  frontend:
    image: registry.skillsnavigator.ru/skills-app-frontend:${TAG}
    container_name: frontend
    build:
      context: ./frontend
    environment:
      VITE_API: /api
      WEB_URL: ${WEB_URL}
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - backend
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
  models:
  postgres: