# docker-compose.override.ci.yml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: local-backend
    ports:
      - "8000:80"

  frontend:
    build:
      context: ./frontend
    image: local-frontend
