import { CardType, MessageType } from './types'

export const cards: CardType[] = [
  {
    id: 1,
    title: 'FastAPI for Beginners',
    cover_url: '/assets/courseImage.png',
    duration: 5,
    pupils_num: 1200,
    difficulty: 'easy',
    price: 0,
    authors: ['Ivan Ivanov'],
    rating: 5,
    url: 'https://example.com/course/1',
  },
  {
    id: 2,
    title: 'Complete Python Course',
    cover_url: '/assets/courseImage.png',
    pupils_num: 1200,
    duration: 40,
    difficulty: 'medium',
    price: 12000,
    authors: ['Maria Petrova', 'Sergey Sidorov'],
    rating: 4,
    url: 'https://example.com/course/2',
  },
  {
    id: 3,
    title: 'FastAPI for Beginners',
    cover_url: '/assets/courseImage.png',
    pupils_num: 1200,
    duration: 5,
    difficulty: 'easy',
    price: 0,
    authors: ['Ivan Ivanov'],
    rating: 5,
    url: 'https://example.com/course/1',
  },
  {
    id: 4,
    title: 'Complete Python Course',
    cover_url: '/assets/courseImage.png',
    pupils_num: 1200,
    duration: 40,
    difficulty: 'medium',
    price: 12000,
    authors: ['Maria Petrova', 'Sergey Sidorov'],
    rating: 4,
    url: 'https://example.com/course/2',
  },
  {
    id: 5,
    title: 'FastAPI for Beginners',
    cover_url: '/assets/courseImage.png',
    pupils_num: 1200,
    duration: 5,
    difficulty: 'easy',
    price: 0,
    authors: ['Ivan Ivanov'],
    rating: 5,
    url: 'https://example.com/course/1',
  },
  {
    id: 6,
    title: 'Complete Python Course',
    cover_url: '/assets/courseImage.png',
    pupils_num: 1200,
    duration: 40,
    difficulty: 'medium',
    price: 12000,
    authors: ['Maria Petrova', 'Sergey Sidorov'],
    rating: 4,
    url: 'https://example.com/course/2',
  },
]

export const questions: MessageType[] = [
  {text: 'Доброго времени суток! Что вы хотели бы освоить? '},
  {text: 'Какой у вас уже уровень?'},
  {text: 'Какие конкретные навыки вы хотите освоить?'},
  {text: 'Твой план, который приведет к цели:'},
]

export const courses: CardType[] = [
  {
    id: 1,
    title: 'FastAPI for Beginners',
    cover_url: '/assets/courseImage.png',
    duration: 5,
    pupils_num: 1200,
    difficulty: 'easy',
    price: 0,
    authors: ['Ivan Ivanov'],
    rating: 5,
    url: 'https://example.com/course/1',
  },
  {
    id: 2,
    title: 'Complete Python Course',
    cover_url: '/assets/courseImage.png',
    pupils_num: 1200,
    duration: 40,
    difficulty: 'medium',
    price: 12000,
    authors: ['Maria Petrova', 'Sergey Sidorov'],
    rating: 4,
    url: 'https://example.com/course/2',
  },
  {
    id: 3,
    title: 'Advanced FastAPI Techniques',
    cover_url: '/assets/courseImage.png',
    pupils_num: 800,
    duration: 10,
    difficulty: 'hard',
    price: 15000,
    authors: ['Alexey Smirnov'],
    rating: 5,
    url: 'https://example.com/course/3',
  }
]
