name: CI

on:
  push:
    branches: [ master, develop, devops ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master, develop, devops ]

env:
  COMPOSE_PROJECT_NAME: dev

jobs:
  build-and-test-backend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Build app
        run: docker compose -f docker-compose.dev.yml build

      - name: Force stop and remove old containers
        run: docker compose -f docker-compose.dev.yml down --volumes

      - name: Start backend services (clean start)
        run: docker compose -f docker-compose.dev.yml up -d --force-recreate --remove-orphans

      - name: Build test container
        run: |
          docker build \
            --file backend/Dockerfile.test \
            --tag test-runner \
            backend

      - name: Run unit and integration tests
        run: docker run --network=host test-runner pytest tests/unit tests/integration

      - name: Wait for backend
        run: docker run --network=host test-runner python wait-for-backend.py

      - name: Run e2e tests
        run: docker run --network=host test-runner pytest tests/e2e

      - name: Shutdown
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v

  test-frontend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.5 --activate

      - name: Install dependencies and run frontend tests
        working-directory: frontend
        run: |
          pnpm install
          pnpm test

  build-and-push-to-docker-registry:
    needs: [ build-and-test-backend, test-frontend ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted

    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}

    env:
      REGISTRY: registry.skillsnavigator.ru

    steps:
      - uses: actions/checkout@v3

      - name: Extract tag and export TAG
        id: extract_tag
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build all services
        run: docker compose -f docker-compose.yml build

      - name: Push all images
        run: docker compose -f docker-compose.yml push
