name: CD-Production

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts

      - name: Pull and deploy containers from registry
        env:
          TAG: ${{ github.sha }}
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "bash -s" <<EOF
          set -e

          docker login registry.skillsnavigator.ru -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
          docker pull registry.skillsnavigator.ru/skills-app-backend:$TAG
          docker pull registry.skillsnavigator.ru/skills-app-frontend:$TAG

          cd /home/${{ secrets.PRODUCTION_USER }}/skillsnavigator

          echo "TAG=$TAG" >> .env

          docker compose pull
          docker compose up -d --remove-orphans --force-recreate
          EOF
