name: CD-Production

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.skillsnavigator.ru
      TAG: ${{ github.event.release.tag_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts

      - name: Pull and deploy containers from registry
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} bash -s <<EOF
            set -e

            docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
            docker pull ${{ env.REGISTRY }}/skills-app-backend:${TAG}
            docker pull ${{ env.REGISTRY }}/skills-app-frontend:${TAG}

            cd /home/${{ secrets.PRODUCTION_USER }}/skillsnavigator

            echo "TAG=$TAG" > .env

            docker compose pull
            docker compose up -d --remove-orphans --force-recreate
          EOF
