name: Deploy to Staging

on:
  push:
    branches: [main, deploy]  # Запуск на пуш в ветки main и tests
  pull_request:
    branches: [main, deploy]  # Запуск на pull request в main и tests

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync project to server
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}:/home/${{ secrets.STAGING_USER }}/skillsnavigator/

      - name: Restart Docker container on server
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} << 'EOF'
          cd /home/${{ secrets.STAGING_USER }}/skillsnavigator
          docker compose pull || true
          docker compose down || true
          docker compose up -d
          EOF
