name: CD-Staging

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      startsWith(github.event.workflow_run.head_branch, 'v')
    name: Deploy to Staging Server
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

      - name: Pull and deploy containers from registry
        env:
          REGISTRY: registry.skillsnavigator.ru
          TAG: ${{ github.event.workflow_run.head_branch }}  # <-- здесь будет v2.0.2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} "bash -s" <<EOF
            set -e

            docker login $REGISTRY -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
            docker pull $REGISTRY/skills-app-backend:$TAG
            docker pull $REGISTRY/skills-app-frontend:$TAG

            cd /home/${{ secrets.STAGING_USER }}/skillsnavigator
            sed -i '/^TAG=/d' .env || true
            echo "TAG=$TAG" >> .env

            docker compose pull
            docker compose up -d --remove-orphans --force-recreate
          EOF